<a href="https://colab.research.google.com/github/Edesak/tensorflow-kurz/blob/main/00_tensorflow_fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Zaklady Tensorflow

##Uvod do tensorflow


In [ ]:
import tensorflow as tf 
print(tf.__version__)


2.5.0


In [ ]:
# Vytvoreni konstanty
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Zkontrolovani dimenze
scalar.ndim

0

In [ ]:
#Vytvoreni vektoru
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#Vytvoreni matice
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Specifikace typu, urceni typu muze ovlivnit velikost tensoru, ktery se uklada do pameti
matrix2= tf.constant([[10.,7.],[3.,2.],[8.,8.]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  8.]], dtype=float16)>

In [ ]:
matrix2.ndim

2

In [ ]:
tensor = tf.constant([[
                      [[1,2,3],[4,5,6]],
                      [[7,8,9],[1,2,3]],
                      [[4,5,6],[7,8,9]]
                      ],
                      [[[1,2,3],[4,5,6]],
                      [[7,8,9],[1,2,3]],
                      [[4,5,6],[7,8,9]]]
                      ])
tensor

<tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [1, 2, 3]],

        [[4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [1, 2, 3]],

        [[4, 5, 6],
         [7, 8, 9]]]], dtype=int32)>

In [ ]:
tensor.ndim

4

##Vytroverni tensoru pomoci promenne (variable)

In [ ]:

var_tensor = tf.Variable([10,7])
unch_tensor = tf.constant([10,7])

var_tensor,unch_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Zkusime zmenit tensor

var_tensor[0] = 7
unch_tensor

TypeError: ignored

In [ ]:
var_tensor[0].assign(7)
var_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unch_tensor [0] = 7

TypeError: ignored

In [ ]:
unch_tensor[0].assign(7)

AttributeError: ignored

##Vytvoreni nahodneho tensoru


In [ ]:
#Nahodny tensor s nahodnymi cisli, pouziva se pri startovni pozici pro NN

random1 = tf.random.Generator.from_seed(42)
random2 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,4))
random2 = random2.normal(shape=(3,4))
random1,random2, random1 == random2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

In [ ]:
#Zmeneni poradi v random tensoru (uzitecne pro mixovani dat aby nebyly po sobe)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]
                            ])
not_shuffled
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) #globalni seed
shuffled = tf.random.shuffle(not_shuffled, seed=42) #operativni seed
shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

##Vytvareni Tensoru jinak
Muzeme vytvorit tensor z Numpy array, rozdil je v tom ze tensor dokaze pracovat s GPU takze je mnohem rychlejsi pri uceni

In [ ]:
#jak udelat tensory jinak

tf.ones([10,7]) #vyplni tensor plny 1
tf.zeros([10,7])#vyplni tensor plny 0

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#Numpy na Tensor

import numpy as np
numpy_A = np.arange (1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4)) # shape musi by roven poctu typu 24 se musi rovnat 2*3*4
B= tf.constant(numpy_A)
A,B,A.ndim

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 3)

##Ziskani informaci z Tensoru
-Rank - dimension\
-Shape - shape(tvar)\
-Axis - sloupce řádky konktrétní dimenze\
-Size - pocet prvku v tensoru

In [ ]:
#Vytvorit rank4 tensor

r_4_tensor=tf.zeros([5,6,7,8])
r_4_tensor, r_4_tensor.ndim

(<tf.Tensor: shape=(5, 6, 7, 8), dtype=float32, numpy=
 array([[[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
 
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
 
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
 
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 

In [ ]:
r_4_tensor.shape, r_4_tensor.ndim, tf.size(r_4_tensor)

(TensorShape([5, 6, 7, 8]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=1680>)

In [ ]:
#Pro lepe cteni tensoru

print(f"Datatype of tensor: {r_4_tensor.dtype}")
print(f"Dimenze tensoru: {r_4_tensor.ndim}")
print(f"Tvar tensoru: {r_4_tensor.shape}")
print(f"Pocet elementu 0 axis: {r_4_tensor.shape[0]}")
print(f"Pocet elementu posledni axis: {r_4_tensor.shape[-1]}")
print(f"Pocet elementu v tensoru: {tf.size(r_4_tensor)}")

Datatype of tensor: <dtype: 'float32'>
Dimenze tensoru: 4
Tvar tensoru: (5, 6, 7, 8)
Pocet elementu 0 axis: 5
Pocet elementu posledni axis: 8
Pocet elementu v tensoru: 1680


##Indexing tensors


In [ ]:
#Prvni 2 elementy z tensoru
r_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#prvni elementy z dimenzi az na posledni dimenzi
r_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 8), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Udelat rank2 tensor
r2_tensor = tf.random.uniform([5,6])
r2_tensor,r2_tensor.ndim

(<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
         0.68467236],
        [0.74011743, 0.8724445 , 0.22632635, 0.22319686, 0.3103881 ,
         0.7223358 ],
        [0.13318717, 0.5480639 , 0.5746088 , 0.8996835 , 0.00946367,
         0.5212307 ],
        [0.6345445 , 0.1993283 , 0.72942245, 0.54583454, 0.10756552,
         0.6767061 ],
        [0.6602763 , 0.33695042, 0.60141766, 0.21062577, 0.8527372 ,
         0.44062173]], dtype=float32)>, 2)

In [ ]:
#Posledni elemety vsech dimenzi
r2_tensor[:,-1:]

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.68467236],
       [0.7223358 ],
       [0.5212307 ],
       [0.6767061 ],
       [0.44062173]], dtype=float32)>

In [ ]:
#Pridani dimenze, misto na kazde dimenzi davat :,:,: nahradit za ...
r3_tensor = r2_tensor[...,tf.newaxis]
r3_tensor

<tf.Tensor: shape=(5, 6, 1), dtype=float32, numpy=
array([[[0.6645621 ],
        [0.44100678],
        [0.3528825 ],
        [0.46448255],
        [0.03366041],
        [0.68467236]],

       [[0.74011743],
        [0.8724445 ],
        [0.22632635],
        [0.22319686],
        [0.3103881 ],
        [0.7223358 ]],

       [[0.13318717],
        [0.5480639 ],
        [0.5746088 ],
        [0.8996835 ],
        [0.00946367],
        [0.5212307 ]],

       [[0.6345445 ],
        [0.1993283 ],
        [0.72942245],
        [0.54583454],
        [0.10756552],
        [0.6767061 ]],

       [[0.6602763 ],
        [0.33695042],
        [0.60141766],
        [0.21062577],
        [0.8527372 ],
        [0.44062173]]], dtype=float32)>

In [ ]:
#alternativa
tf.expand_dims(r2_tensor,axis=-1) #-1 posledni axis pridat dimenzi 

#tf.expand_dims(r2_tensor,axis=1) 

<tf.Tensor: shape=(5, 6, 1), dtype=float32, numpy=
array([[[0.6645621 ],
        [0.44100678],
        [0.3528825 ],
        [0.46448255],
        [0.03366041],
        [0.68467236]],

       [[0.74011743],
        [0.8724445 ],
        [0.22632635],
        [0.22319686],
        [0.3103881 ],
        [0.7223358 ]],

       [[0.13318717],
        [0.5480639 ],
        [0.5746088 ],
        [0.8996835 ],
        [0.00946367],
        [0.5212307 ]],

       [[0.6345445 ],
        [0.1993283 ],
        [0.72942245],
        [0.54583454],
        [0.10756552],
        [0.6767061 ]],

       [[0.6602763 ],
        [0.33695042],
        [0.60141766],
        [0.21062577],
        [0.8527372 ],
        [0.44062173]]], dtype=float32)>

## Tensor operace

In [ ]:
#Zakladni operace tensoru
tensor = tf.constant([[10,7],
                      [3,4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor -10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
#Muzeme take pozit promo knihovnu tf rozdil mezi obycejnym a tf knihovnou je to ze TF vyuziva GPU coz je rychlejsi pri vetsich tensorech
tf.math.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.math.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tf.math.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

##Operace s maticemi (tensory)
Nejbeznejsi operace

1. Vnitrni cisla matice musi sedet [2:3] [3:2] jde [5:6] [3:3] nejde
2. Vysledna matice je rozmerove vzdalene cisla [2:3] [3:2] vysledna matice je [2:2]

In [ ]:
#nasobeni matic
print(tensor)
tf.linalg.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
mat1 = tf.constant([[1,2,1],
                    [0,1,0],
                    [2,3,4]])
mat2 = tf.constant([[2,5],
                    [6,7],
                    [1,8]])
tf.linalg.matmul(mat1,mat2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [ ]:
#Pocitani v Pythonu s maticemi
mat1 @ mat2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [ ]:
tf.linalg.matmul(mat2,mat2,transpose_a=True), tf.linalg.matmul(mat2,mat2,transpose_b=True)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 41,  60],
        [ 60, 138]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[29, 47, 42],
        [47, 85, 62],
        [42, 62, 65]], dtype=int32)>)

##Zmena typu data
defaultni je 32 bit muzeme vsak premenit na 16bit coz zabira min mista v pameti a je rychlejsi. Zauctuje se to vsak na presnosti modelu. 

In [ ]:
B= tf.constant([1.7,2.8,3.5])
C = tf.constant([1,2,3])
B.dtype,C.dtype

(tf.float32, tf.int32)

In [ ]:
D = tf.cast(B,dtype=tf.float16)
D.dtype, B.dtype

(tf.float16, tf.float32)

In [ ]:
E = tf.cast(C,dtype=tf.float32)
C.dtype, E.dtype 

(tf.int32, tf.float32)

##Agregace (Aggregation tensors)
Zredukovani vicero hodnot na mene hodnot

In [ ]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Formy agregace
* Maximum
* Minimum
* Prumer
* Soucet

In [ ]:
tf.random.set_seed(42)
random3 = tf.random.uniform([50,50,50],seed=42,minval=0,maxval=100)
print(f"Maximalni hodnota v tensoru: {tf.math.reduce_max(random3)}")
print(f"Minimalni hodnota v tensoru: {tf.math.reduce_min(random3)}")
print(f"Prumerna hodnota v tensoru: {tf.math.reduce_mean(random3)}")
print(f"Soucet hodnot v tensoru: {tf.math.reduce_sum(random3)}")

Maximalni hodnota v tensoru: 99.99900817871094
Minimalni hodnota v tensoru: 0.0017404556274414062
Prumerna hodnota v tensoru: 50.010311126708984
Soucet hodnot v tensoru: 6251289.0


##Směrodatná odchylka a rozptyl
Rozptyl je jak moc jsou hodnoty rozptýlene od průměrné hodnoty.\
Zatím co směrodatná odchylka je odmocnina z rozptylu.

In [ ]:
print(f"Rozptyl matice: {tf.math.reduce_variance(random3)}")
print(f"Smerodatna odchylka matice: {tf.math.reduce_std(random3)}")

Rozptyl matice: 831.886474609375
Smerodatna odchylka matice: 28.84244155883789


##Zjisteni pozice maximalni a minimalni hodnoty
Tato funkce funguje podle ocekavani (ze vrati pouze jednu hodnotu, ktera obsahuje index, kde je nevyssi hodnota) pouze u 1 dim

In [ ]:
print(f"Maximalni hodnota je na pozici: {tf.math.argmax(random3)}")
print(f"Minimalni hodnota je na pozici: {tf.math.argmin(random3)}")
print("\n")
print(f"Tato funkce funguje podle ocekavani (ze vrati pouze jednu hodnotu, ktera obsahuje index, kde je nevyssi hodnota) pouze u 1 dim ")
print("\n")
tf.random.set_seed(42)
random4 = tf.random.uniform([50])
print(random4)
print("\n")
print(f"Maximalni hodnota 1dim je na pozici: {tf.math.argmax(random4)}")
print(f"Minimalni hodnota 1dim je na pozici: {tf.math.argmin(random4)}")
print(f"Maximalni hodnota: {random4[tf.math.argmax(random4)]}")
print(f"Minimalni hodnota: {random4[tf.math.argmin(random4)]}")
#tf.math.argmax(tf.math.argmax(tf.math.argmax(random3)))

Maximalni hodnota je na pozici: [[10  1 34 ...  4 13 17]
 [34 13 45 ... 30 46 42]
 [22 21 12 ... 32 15 13]
 ...
 [10 40 31 ... 22  9 31]
 [24 12  1 ... 32 49 49]
 [29 17 41 ... 41  7 44]]
Minimalni hodnota je na pozici: [[26  3 33 ...  7 10 47]
 [ 4 45 42 ...  7 40 49]
 [39 20 42 ...  4  7 42]
 ...
 [45 33 14 ... 21 28 12]
 [ 9 11  0 ... 33 30 17]
 [28  9 34 ... 40 41 31]]


Tato funkce funguje podle ocekavani (ze vrati pouze jednu hodnotu, ktera obsahuje index, kde je nevyssi hodnota) pouze u 1 dim 


tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
 0.9671384  0.06

##Zmacknuti tensoru (Squeezing tensor)
Odstranovani 1 dim prebytecnych

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform([50]),shape=(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[[[[[[[[[[[0.6645621 , 0.44100678, 0.3528825 ,
                      0.46448255, 0.03366041, 0.68467236,
                      0.74011743, 0.8724445 , 0.22632635,
                      0.22319686, 0.3103881 , 0.7223358 ,
                      0.13318717, 0.5480639 , 0.5746088 ,
                      0.8996835 , 0.00946367, 0.5212307 ,
                      0.6345445 , 0.1993283 , 0.72942245,
                      0.54583454, 0.10756552, 0.6767061 ,
                      0.6602763 , 0.33695042, 0.60141766,
                      0.21062577, 0.8527372 , 0.44062173,
                      0.9485276 , 0.23752594, 0.81179297,
                      0.5263394 , 0.494308  , 0.21612847,
                      0.8457197 , 0.8718841 , 0.3083862 ,
                      0.6868038 , 0.23764038, 0.7817228 ,
                      0.9671384 , 0.06870162, 0.79873943,
                      0.66028714, 0.587

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

##One-hot Encoding tensor

In [ ]:
some_list = [0,1,2]  #red,green,blue

tf.one_hot(some_list,depth=3)
#vytvori z indicii tensor, ktery na kazdem radku ma specifikaci o jaky typ jde 1. radek red 2. radek green 3.radek blue

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
#Specifikace vlastnich hodnot na one_hot (v praxi nepouziva se)
tf.one_hot(some_list,depth=3,on_value="on",off_value="off")

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'on', b'off', b'off'],
       [b'off', b'on', b'off'],
       [b'off', b'off', b'on']], dtype=object)>

##Bezne matematicke operace
* Log
* Odmocnina
* Mocnina

In [ ]:
H= tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,tf.float32)) #Nesmi byt int type

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,tf.float32)) #Nesmi byt int type

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

##Tensor a NumPy
TensorFlow pracuje krasne NumPy array

In [ ]:
#Vytvoreni tensoru z NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Konverce zpet na NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#Defaultni typy

np_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
#Pozor na typ pri vytvareni a konvertovani. 
np_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

##Access to GPU
Runtime -> Changeruntime


In [ ]:
import tensorflow as tf
tf.config.list_logical_devices("GPU")


[LogicalDevice(name='/device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Jun 30 20:51:29 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P0    30W /  70W |    222MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

##Cviceni
* Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
* Find the shape, rank and size of the tensors you created in 1.
*Create two tensors containing random values between 0 and 1 with shape [5, 300].
* Multiply the two tensors you created in 3 using matrix multiplication.
* Multiply the two tensors you created in 3 using dot product. (Znovu se kouknout)
* Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
* Find the min and max values of the tensor you created in 6 along the first axis.
* Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
* Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
* One-hot encode the tensor you created in 9

In [ ]:
import numpy as np

#1 a #2
t_s = tf.constant(1)
t_v = tf.constant([1,2])
t_m = tf.constant([[1,2],
                   [3,4]])
t_t = tf.constant([[[1,2],
                   [3,4]],
                  [[5,6],
                   [7,8]]])
print(f"Rank of scalar:{t_s.ndim}")
print(f"Rank of vector:{t_v.ndim}")
print(f"Rank of matrix:{t_m.ndim}")
print(f"Rank of tensor:{t_t.ndim}")

print(f"Shape of scalar:{t_s.shape}")
print(f"Shape of vector:{t_v.shape}")
print(f"Shape of matrix:{t_m.shape}")
print(f"Shape of tensor:{t_t.shape}")

print(f"Size of scalar:{tf.size(t_s)}")
print(f"Size of vector:{tf.size(t_v)}")
print(f"Size of matrix:{tf.size(t_m)}")
print(f"Size of tensor:{tf.size(t_t)}")


In [ ]:
t_random1 = tf.random.uniform(shape=(5,300),minval=0,maxval=1)
t_random2 = tf.random.uniform(shape=(5,300),minval=0,maxval=1)

t_random1,t_random2

In [ ]:
tf.linalg.matmul(t_random1,t_random2,transpose_b=True)

In [ ]:
t_random3 = tf.random.uniform(shape=(224,224,1))
t_random3

In [ ]:
tf.math.reduce_max(t_random3)


In [ ]:
tf.math.reduce_min(t_random3)

In [ ]:
t_random4 = tf.random.uniform(shape=(1,224,224,3))
print(t_random4.shape)
t_random4_sq = tf.squeeze(t_random4)
print(t_random4_sq.shape)


In [ ]:
t_in_max = tf.constant(np.arange(0,10,1))
print(t_in_max[:5])
print(t_in_max.shape)
print(t_in_max)
print(tf.math.argmax(t_in_max))
print(t_in_max[tf.math.argmax(t_in_max)])

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
(10,)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


In [ ]:
print(tf.cast(t_in_max,tf.int32))
tf.one_hot(tf.cast(t_in_max,tf.int32),depth=10)